"use client";

import { Document, Image, Page, Text, View } from "@react-pdf/renderer";
import { format } from "date-fns";
import { styles } from "./style";
import { THEME } from "./theme";

const ITEM_PER_PAGE = 25;

const columns = ["DATETIME", "TEMP °C", "RH %"];
const columnWidths = [1.8, 0.6, 0.6];

export default function CommonReportPDF({ data = [], filter, name }) {
  return (
    <Document>
      {data.map((room) => {
        const logs = room.logs ?? [];
        const pages = [];
        pages.push(logs.slice(0, 20));
        for (let i = 20; i < logs.length; i += ITEM_PER_PAGE) {
          pages.push(logs.slice(i, i + ITEM_PER_PAGE));
        }

        return pages.map((pageRows, pageIndex) => (
          <Page
            key={`${room.roomId}-${pageIndex}`}
            size="A4"
            style={styles.page}
          >
            {/* HEADER */}

            <View style={styles.header}>
              <Image src="/logo.jpg" style={styles.icon} />

              <View style={{ alignItems: "flex-end" }}>
                <Text
                  style={{
                    fontSize: 10,
                    color: THEME.main,
                    fontWeight: "bold",
                  }}
                >
                  Generated By: <Text>{name}</Text>
                </Text>

                <Text style={{ fontSize: 9 }}>
                  {format(new Date(), "dd MMM yyyy")} -{" "}
                  {format(new Date(), "hh:mm:ss a")}
                </Text>
              </View>
            </View>

            {/* REPORT HEADER */}

            {pageIndex === 0 && (
              <>
                <Text style={styles.title}>MULTIPLE ROOM REPORT</Text>

                <View style={styles.gridContainer}>
                  <View style={styles.gridRow}>
                    <Text style={styles.label}>Room :</Text>
                    <Text>{room.roomName}</Text>
                  </View>
                  <View style={styles.gridRow}>
                    <Text style={styles.label}>Category :</Text>
                    <Text>{filter.categoryName}</Text>
                  </View>
                  <View style={styles.gridRow}>
                    <Text style={styles.label}>Interval :</Text>
                    <Text>{filter.interval} Minutes</Text>
                  </View>
                  <View style={styles.gridRow}>
                    <Text style={styles.label}>Duration :</Text>
                    <Text>
                      {format(new Date(filter.fromDate), "dd-MMM-yyyy hh:mm a")}{" "}
                      - {format(new Date(filter.toDate), "dd-MMM-yyyy hh:mm a")}
                    </Text>
                  </View>

                  <View style={styles.gridRow}>
                    <Text style={styles.label}>Total Records :</Text>
                    <Text>{logs.length}</Text>
                  </View>
                </View>

                <Text
                  style={{
                    marginTop: 12,
                    marginBottom: 6,
                    fontSize: 12,
                    fontWeight: "bold",
                    color: THEME.main,
                  }}
                >
                  DETAIL LOG
                </Text>
              </>
            )}

            {/* TABLE */}

            <View style={styles.tableContainer}>
              <View style={styles.tableHeader}>
                {columns.map((column, index) => (
                  <Text
                    key={index}
                    style={[
                      styles.tableHeaderText,
                      {
                        flex: columnWidths[index],
                      },
                    ]}
                  >
                    {column}
                  </Text>
                ))}
              </View>

              {pageRows.map((log, index) => (
                <View
                  key={index}
                  style={[
                    styles.tableRow,
                    index % 2 === 1 && {
                      backgroundColor: THEME.card,
                    },
                  ]}
                >
                  <Text
                    style={[
                      styles.tableCell,
                      {
                        flex: columnWidths[0],
                      },
                    ]}
                  >
                    {format(new Date(log.timeStamp), "dd MMM yyyy hh:mm a")}
                  </Text>

                  <Text
                    style={[
                      styles.tableCell,
                      {
                        flex: columnWidths[1],
                      },
                    ]}
                  >
                    {Number(log.avgTemp ?? 0).toFixed(1)}
                  </Text>

                  <Text
                    style={[
                      styles.tableCell,
                      {
                        flex: columnWidths[2],
                      },
                    ]}
                  >
                    {Number(log.rh ?? 0).toFixed(2)}
                  </Text>
                </View>
              ))}
            </View>

            {/* FOOTER */}

            <View
              fixed
              style={{
                position: "absolute",
                left: 25,
                right: 25,
                bottom: 15,
                borderTop: `1px solid ${THEME.border}`,
                paddingTop: 5,
                flexDirection: "row",
                justifyContent: "space-between",
                fontSize: 8,
                color: "#666",
              }}
            >
              <Text>JWR Monitoring System</Text>

              <Text
                render={({ pageNumber, totalPages }) =>
                  `Page ${pageNumber} of ${totalPages}`
                }
              />
            </View>
          </Page>
        ));
      })}
    </Document>
  );
}
