"use client";

import { Document, Image, Page, Text, View } from "@react-pdf/renderer";
import { format } from "date-fns";
import { styles } from "./style";
import { THEME } from "./theme";

const ROOMS_PER_PAGE = 3;
const ROWS_PER_PAGE = 24;

export default function EnergyReportPDF({ data = [], filter, name }) {
  if (!data.length) return <Document />;

  // Split rooms into groups of 5
  const roomGroups = [];
  for (let i = 0; i < data.length; i += ROOMS_PER_PAGE) {
    roomGroups.push(data.slice(i, i + ROOMS_PER_PAGE));
  }

  return (
    <Document>
      {roomGroups.map((rooms, groupIndex) => {
        // create rows from first room timestamps
        const rows = rooms[0].logs.map((_, index) => ({
          timeStamp: rooms[0].logs[index]?.timeStamp,
          values: rooms.map((room) => room.logs[index] ?? {}),
        }));

        const pages = [];

        for (let i = 0; i < rows.length; i += ROWS_PER_PAGE) {
          pages.push(rows.slice(i, i + ROWS_PER_PAGE));
        }

        return pages.map((pageRows, pageIndex) => (
          <Page
            key={`${groupIndex}-${pageIndex}`}
            size="A4"
            style={styles.page}
          >
            {/* ================= HEADER ================= */}

            <View style={styles.header}>
              <Image src="/logo.jpg" style={styles.icon} />

              <View style={{ alignItems: "flex-end" }}>
                <Text
                  style={{
                    fontSize: 10,
                    color: THEME.main,
                    fontWeight: "bold",
                  }}
                >
                  COLD STORAGE, JNPT, NAVI MUMBAI
                </Text>
                <Text style={{ fontSize: 9 }}>
                  {format(new Date(), "dd MMM yyyy")} -{" "}
                  {format(new Date(), "hh:mm:ss a")}
                </Text>
              </View>
            </View>

            {/* ================= REPORT DETAILS ================= */}

            <Text style={styles.title}>Energy Room</Text>

            <View style={styles.gridContainer}>
              <View style={styles.gridRow}>
                <Text style={styles.label}>Generated By : </Text>
                <Text>{name}</Text>
              </View>
              <View style={styles.gridRow}>
                <Text style={styles.label}>Category :</Text>
                <Text>{filter.categoryName}</Text>
              </View>

              <View style={styles.gridRow}>
                <Text style={styles.label}>Interval :</Text>
                <Text>{filter.interval} Minutes</Text>
              </View>

              <View style={styles.gridRow}>
                <Text style={styles.label}>Duration :</Text>
                <Text>
                  {format(new Date(filter.fromDate), "dd MMM yyyy hh:mm a")} -{" "}
                  {format(new Date(filter.toDate), "dd MMM yyyy hh:mm a")}
                </Text>
              </View>

              <View style={styles.gridRow}>
                <Text style={styles.label}>Rooms :</Text>
                <Text>{data.map((r) => r.roomName).join(", ")}</Text>
              </View>

              <View style={styles.gridRow}>
                <Text style={styles.label}>Records :</Text>
                <Text>{rows.length}</Text>
              </View>
            </View>

            <Text
              style={{
                marginTop: 12,
                marginBottom: 6,
                fontSize: 12,
                fontWeight: "bold",
                color: THEME.main,
              }}
            >
              DETAIL LOG
            </Text>

            {/* ================= TABLE ================= */}

            <View
              style={{
                borderWidth: 1,
                borderColor: THEME.border,
              }}
            >
              {/* Header Row 1 */}

              <View
                style={{
                  flexDirection: "row",
                  backgroundColor: THEME.main,
                  color: "#fff",
                  borderBottomWidth: 1,
                  borderColor: THEME.border,
                  minHeight: 20,
                }}
              >
                <View
                  style={{
                    width: 100,
                    justifyContent: "center",
                    alignItems: "center",
                    borderRightWidth: 1,
                    borderColor: "#fff",
                    paddingVertical: 8,
                  }}
                >
                  <Text
                    style={{
                      fontSize: 9,
                      fontWeight: "bold",
                    }}
                  >
                    DATETIME
                  </Text>
                </View>

                {rooms.map((room) => (
                  <View
                    key={room.roomId}
                    style={{
                      flex: 2,
                      justifyContent: "center",
                      alignItems: "center",
                      borderRightWidth: 1,
                      borderColor: "#fff",
                      paddingVertical: 8,
                    }}
                  >
                    <Text
                      style={{
                        fontSize: 9,
                        fontWeight: "bold",
                      }}
                    >
                      {room.roomName}
                    </Text>
                  </View>
                ))}
              </View>

              {/* Header Row 2 */}

              <View
                style={{
                  flexDirection: "row",
                  backgroundColor: THEME.main,
                  color: "#fff",
                  borderBottomWidth: 1,
                  borderColor: THEME.border,
                  minHeight: 20,
                }}
              >
                <View
                  style={{
                    width: 100,
                    borderRightWidth: 1,
                    borderColor: "#fff",
                  }}
                />

                {rooms.map((room) => (
                  <View
                    key={room.roomId}
                    style={{
                      flex: 2,
                      flexDirection: "row",
                      borderRightWidth: 1,
                      borderColor: "#fff",
                    }}
                  >
                    <View
                      style={{
                        flex: 1,
                        alignItems: "center",
                        borderRightWidth: 1,
                        borderColor: "#fff",
                        paddingVertical: 5,
                      }}
                    >
                      <Text
                        style={{
                          fontSize: 8,
                          fontWeight: "bold",
                          textAlign: "center",
                        }}
                      >
                        {`Energy\nkWh`}
                      </Text>
                    </View>

                    <View
                      style={{
                        flex: 1,
                        alignItems: "center",
                        borderRightWidth: 1,
                        borderColor: "#fff",
                        paddingVertical: 5,
                      }}
                    >
                      <Text
                        style={{
                          fontSize: 8,
                          fontWeight: "bold",
                          textAlign: "center",
                        }}
                      >
                        {`Current\nA`}
                      </Text>
                    </View>
                    <View
                      style={{
                        flex: 1,
                        alignItems: "center",
                        borderRightWidth: 1,
                        borderColor: "#fff",
                        paddingVertical: 5,
                      }}
                    >
                      <Text
                        style={{
                          fontSize: 8,
                          fontWeight: "bold",
                          textAlign: "center",
                        }}
                      >
                        {`Voltage\nV`}
                      </Text>
                    </View>
                    <View
                      style={{
                        flex: 1,
                        alignItems: "center",
                        paddingVertical: 5,
                      }}
                    >
                      <Text
                        style={{
                          fontSize: 8,
                          fontWeight: "bold",
                          textAlign: "center",
                        }}
                      >
                        {`Freq\nHz`}
                      </Text>
                    </View>
                  </View>
                ))}
              </View>

              {/* BODY */}

              {pageRows.map((row, rowIndex) => (
                <View
                  key={rowIndex}
                  style={{
                    flexDirection: "row",
                    backgroundColor: rowIndex % 2 ? THEME.card : "#fff",
                    borderBottomWidth: 1,
                    borderColor: THEME.border,
                    minHeight: 20,
                  }}
                >
                  <View
                    style={{
                      width: 100,
                      borderRightWidth: 1,
                      borderColor: THEME.border,
                      justifyContent: "center",
                      paddingHorizontal: 5,
                    }}
                  >
                    <Text style={{ fontSize: 8 }}>
                      {format(new Date(row.timeStamp), "dd MMM yyyy hh:mm a")}
                    </Text>
                  </View>

                  {row.values.map((log, i) => (
                    <View
                      key={i}
                      style={{
                        flex: 2,
                        flexDirection: "row",
                        borderRightWidth: 1,
                        borderColor: THEME.border,
                      }}
                    >
                      <View
                        style={{
                          flex: 1,
                          alignItems: "center",
                          justifyContent: "center",
                          borderRightWidth: 1,
                          borderColor: THEME.border,
                        }}
                      >
                        <Text style={{ fontSize: 8 }}>
                          {log.energy != null
                            ? Number(log.energy).toFixed(2)
                            : "-"}
                        </Text>
                      </View>

                      <View
                        style={{
                          flex: 1,
                          alignItems: "center",
                          justifyContent: "center",
                          borderRightWidth: 1,
                          borderColor: THEME.border,
                        }}
                      >
                        <Text style={{ fontSize: 8 }}>
                          {log.current != null
                            ? Number(log.current).toFixed(2)
                            : "-"}
                        </Text>
                      </View>
                      <View
                        style={{
                          flex: 1,
                          alignItems: "center",
                          justifyContent: "center",
                          borderRightWidth: 1,
                          borderColor: THEME.border,
                        }}
                      >
                        <Text style={{ fontSize: 8 }}>
                          {log.voltage != null
                            ? Number(log.voltage).toFixed(2)
                            : "-"}
                        </Text>
                      </View>
                      <View
                        style={{
                          flex: 1,
                          alignItems: "center",
                          justifyContent: "center",
                        }}
                      >
                        <Text style={{ fontSize: 8 }}>
                          {log.frequency != null
                            ? Number(log.frequency).toFixed(2)
                            : "-"}
                        </Text>
                      </View>
                    </View>
                  ))}
                </View>
              ))}
            </View>

            {/* ================= FOOTER ================= */}

            <View
              fixed
              style={{
                position: "absolute",
                left: 25,
                right: 25,
                bottom: 15,
                borderTop: `1px solid ${THEME.border}`,
                paddingTop: 5,
                flexDirection: "row",
                justifyContent: "space-between",
                fontSize: 8,
                color: "#666",
              }}
            >
              <Text
                render={({ pageNumber, totalPages }) =>
                  `Page ${pageNumber} of ${totalPages}`
                }
              />
            </View>
          </Page>
        ));
      })}
    </Document>
  );
}
