# ==========================================
# APPLICATION
# ==========================================
spring.application.name=jwr-monitoring

app.ip=192.168.1.230
server.address=${app.ip}
server.port=8080

# ==========================================
# DATABASE
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/jwr-monitoring
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# ==========================================
# SPRING BOOT
# ==========================================
spring.main.banner-mode=off
logging.level.org.apache.plc4x=OFF
logging.level.org.apache.plc4x.java.spi.connection=ERROR
logging.level.io.netty=ERROR
logging.level.io.netty.channel=OFF
logging.level.io.netty.util=OFF

# Security
logging.level.org.springframework.security=OFF

# Hibernate SQL
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF